version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - cd TeamFourmen
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - TeamFourmen/build/libs/TeamFourmen-0.0.1-SNAPSHOT.jar
  discard-paths: yes