version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - cd TeamFourmen
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo Build completed successfully
      - zip -r fourmen.zip build/libs/TeamFourmen-0.0.1-SNAPSHOT.jar appspec.yml scripts/server_start.sh scripts/server_stop.sh
artifacts:
  files:
    - TeamFourmen/build/libs/TeamFourmen-0.0.1-SNAPSHOT.jar
    - TeamFourmen/appspec.yml
    - TeamFourmen/scripts/server_start.sh
    - TeamFourmen/scripts/server_stop.sh
  discard-paths: yes